### ISSUE TITLE
Replacing a previous digit when the field is not fully filled yet should highlight the next character of the replaced digit

### ISSUE THREAD

**Issue by michael-jong-ds** [viclafouch/mui-otp-input#20]
For example if we want to type in the code `123456`,
but we missed the `2` (maybe because the keyboard is not working properly), so instead, we type in `13456`

We would have the field like this
`[1] [3] [4] [5] [6] [|]`

then, we would try to correct it by clicking on the digit field with `3` in it

`[1] [3|] [4] [5] [6] []` with `|` as cursor

since the `3` is now highlighted we want to replace it with `2`.
if we type in `2`, then the field state would be like this
`[1] [2] [4] [5] [6] [|]`

the cursor jumps from the 2nd digit field to the unfilled digit
this might be frustrating for user since user has to go back again and again to the previous field to fill everything out.
While the user might be able to fully fill out the digits first, then go back and retype the wrong digits, it would be better experience if we highlight the next character, instead of the next unfilled field.

Expectation: 
`[1] [3|] [4] [5] [6] []`

if we type in `2` from this position
the state should be

`[1] [2] [4|] [5] [6] []`

and then type `3`

`[1] [2] [3] [5|] [6] []`

so we can fill it in with `4`, `5`, and `6`, completing the field.

**Comment by Demetri0** [comment]
Btw... what if the value in a box not selected, but cursor are in a box:

Selected:
![Screenshot from 2023-06-20 18-13-46](https://github.com/viclafouch/mui-otp-input/assets/6806547/1361adcf-86ed-47fd-9dcd-b540eecb76f8)

Value not selected, but cursor in the box:
![Screenshot from 2023-06-20 18-15-14](https://github.com/viclafouch/mui-otp-input/assets/6806547/adfb9fee-a84a-4f9d-95f5-d8447a59a492)

What should happen in the second variant? For now pressing `2` digit doing nothing but just move cursor to the end. Buy my expected behavior is that right part of value should be shifted, so the result should be next:
![Screenshot from 2023-06-20 18-16-53](https://github.com/viclafouch/mui-otp-input/assets/6806547/7294151b-2782-48a7-ad45-915ec70246e0)

**Comment by michael-jong-ds** [comment]
> Behavior that I can expect is that right part of value should be shifted, so the result should be next:

yeah that would be nice, then if the cursor is before the value
![Screenshot from 2023-06-21 09-47-35](https://github.com/viclafouch/mui-otp-input/assets/100671309/e5e29e32-ab11-4d4d-beae-e1e3bca9667b)
it should shift the values to the right

![Screenshot from 2023-06-21 09-49-14](https://github.com/viclafouch/mui-otp-input/assets/100671309/a7596b4b-e07b-496d-8668-b4fa2b8b1ef7)
